#!/usr/bin/env python3
"""Delete Snyk projects for image paths that no longer exist in the published image.

This image ships a pre-warmed maven repository, so snyk's container scan registers one project per
jar *directory* - and those paths embed the version:

    /home/steadybit/.m2/repository/io/netty/netty-transport/4.2.14.Final
    /home/steadybit/.m2/repository/io/netty/netty-transport/4.2.16.Final

Snyk treats those as unrelated projects and never retires the old one (every project keeps reporting
`status: active`), so each dependency bump leaves an orphan behind. The orphans keep reporting
findings against jars the image no longer contains.

Liveness is derived from an SBOM of the published image, because snyk exposes no "last tested"
timestamp on projects (the REST attribute does not exist and /v1/org/{org}/projects is gone). That
also makes this independent of whether a `snyk monitor` has finished processing: a project is stale
purely because its path is absent from the image.

It has to be the image, not maven: `mvn dependency:list` reports only *project* dependencies, while
the image also carries maven's own lib/ jars and every plugin transitive - about 47% of the paths
snyk registers. Resolving liveness from maven would mark those live projects stale and delete them.

Only projects whose name suffix is an absolute container path are ever candidates. Manifest-suffixed
projects (`:go.mod`, `:Dockerfile`, ...) live under the same name prefix but are not image paths, so
they can never appear in the SBOM and must not be judged by it.

Usage:
    export SNYK_TOKEN=...  SNYK_ORG_ID=...
    python3 prune-stale-snyk-projects.py --image ghcr.io/steadybit/extension-gatling:latest
    python3 prune-stale-snyk-projects.py --image ... --apply
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request

API = "https://api.snyk.io"
API_VERSION = "2024-10-15"
TIMEOUT_SECONDS = 60
RETRY_STATUS = {429, 500, 502, 503, 504}
MAX_ATTEMPTS = 5

# A wholesale format change - snyk renaming app projects, or the sbom naming its components
# differently - shows up as *no* project path matching the sbom at all. That is the signal worth
# guarding on. A mid-range ratio would not work: the first real prune here was legitimately 60%
# stale, so anything strict enough to catch drift would also block genuine cleanups.
MAX_PRUNE_RATIO = 0.95


def image_paths(image, org):
    """Every path in the image that snyk treats as its own scan target.

    Generated by snyk rather than trivy so that liveness is decided by the very engine that creates
    the projects - the component names here are the project paths verbatim. Snyk enumerates slightly
    more than trivy does (e.g. `.sbt/1.0/zinc/org.scala-sbt`), and anything snyk sees but we do not
    would be deleted as stale, so its view is the safe one to trust.

    An SBOM rather than `monitor`/`test` output because we want the inventory alone, with no findings.
    """
    out = subprocess.run(
        ["snyk", "container", "sbom", f"--org={org}", "--format=cyclonedx1.6+json", image],
        check=True, capture_output=True, text=True,
    ).stdout
    paths = set()
    for component in json.loads(out).get("components") or []:
        # `ghcr.io/steadybit/extension-gatling:latest:/home/steadybit/.m2/repository/...`
        match = re.search(r":(/.*)$", component.get("name") or "")
        if match:
            paths.add(match.group(1))
    return paths


def request(url, token, method="GET"):
    """Call the snyk REST API, retrying throttles and transient server errors."""
    headers = {"Authorization": f"token {token}"}
    if method == "DELETE":
        headers["Content-Type"] = "application/vnd.api+json"
    for attempt in range(1, MAX_ATTEMPTS + 1):
        try:
            req = urllib.request.Request(url, headers=headers, method=method)
            with urllib.request.urlopen(req, timeout=TIMEOUT_SECONDS) as response:
                body = response.read()
            return json.loads(body) if body else None
        except urllib.error.HTTPError as e:
            if e.code not in RETRY_STATUS or attempt == MAX_ATTEMPTS:
                raise
            delay = int(e.headers.get("Retry-After") or 0) or 2 ** attempt
        except urllib.error.URLError:
            if attempt == MAX_ATTEMPTS:
                raise
            delay = 2 ** attempt
        time.sleep(delay)
    raise AssertionError("unreachable")


def all_projects(org, token):
    url = f"{API}/rest/orgs/{org}/projects?version={API_VERSION}&limit=100"
    projects = []
    while url:
        page = request(url, token)
        projects.extend(page.get("data") or [])
        nxt = (page.get("links") or {}).get("next")
        if isinstance(nxt, dict):
            nxt = nxt.get("href")
        url = (nxt if nxt.startswith("http") else API + nxt) if nxt else None
    return projects


def stale_for_ref(projects, project_name, ref, live):
    """Projects for `ref` whose image path is gone, or None if the paths look untrustworthy."""
    owned = [p for p in projects
             if p["attributes"]["name"].startswith(project_name + ":")
             and p["attributes"].get("target_reference") == ref]
    # Manifest projects (`:go.mod`) share the prefix but are not image paths - never judge them here.
    candidates = [p for p in owned if p["attributes"]["name"].split(":", 1)[1].startswith("/")]
    paths = {p["attributes"]["name"].split(":", 1)[1] for p in candidates}
    orphans = [p for p in candidates if p["attributes"]["name"].split(":", 1)[1] not in live]
    print(f"  [{ref}] {len(owned)} projects "
          f"({len(candidates)} image paths, {len(owned) - len(candidates)} manifest), "
          f"{len(orphans)} stale")

    if not candidates:
        return []
    if not paths & live:
        print(f"::warning::no project path for {ref} appears in the sbom - "
              f"path format changed, refusing to prune")
        return None
    if len(orphans) > MAX_PRUNE_RATIO * len(candidates):
        print(f"::warning::refusing to prune {len(orphans)}/{len(candidates)} for {ref} "
              f"- path matching looks wrong")
        return None
    return orphans


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", required=True,
                        help="image whose contents define what is live")
    parser.add_argument("--project", default=os.environ.get("GITHUB_REPOSITORY"),
                        help="snyk project name prefix, e.g. steadybit/extension-gatling")
    parser.add_argument("--refs", default="latest,release-candidate",
                        help="comma-separated snyk target references to prune")
    parser.add_argument("--apply", action="store_true",
                        help="actually delete; without this it only reports")
    args = parser.parse_args()

    token, org = os.environ.get("SNYK_TOKEN"), os.environ.get("SNYK_ORG_ID")
    if not token or not org:
        sys.exit("SNYK_TOKEN and SNYK_ORG_ID must be set")
    if not args.project:
        sys.exit("--project is required when GITHUB_REPOSITORY is unset")

    live = image_paths(args.image, org)
    if not live:
        sys.exit(f"sbom for {args.image} listed no scan targets - refusing to prune")
    print(f"{args.image}: {len(live)} live paths")

    # `:rc` and `:latest` are the same build at release time, so one inventory covers both refs.
    projects = all_projects(org, token)
    stale, skipped = [], []
    for ref in [r.strip() for r in args.refs.split(",") if r.strip()]:
        orphans = stale_for_ref(projects, args.project, ref, live)
        if orphans is None:
            skipped.append(ref)
        else:
            stale.extend(orphans)

    if not stale:
        print("nothing to prune")
        sys.exit(1 if skipped else 0)
    if not args.apply:
        for p in stale[:10]:
            print(f"  would delete {p['attributes']['name']}")
        print(f"{len(stale)} stale projects; re-run with --apply to delete")
        sys.exit(1 if skipped else 0)

    pruned = 0
    failed = []
    for p in stale:
        try:
            request(f"{API}/rest/orgs/{org}/projects/{p['id']}?version={API_VERSION}",
                    token, method="DELETE")
            pruned += 1
        except (urllib.error.HTTPError, urllib.error.URLError) as e:
            reason = getattr(e, "code", e)
            print(f"  failed ({reason}): {p['attributes']['name']}")
            failed.append(p)
    print(f"pruned {pruned}/{len(stale)} stale projects")

    # Surface a red job rather than a green one that quietly pruned nothing.
    if failed:
        sys.exit(f"{len(failed)} deletions failed")
    if skipped:
        sys.exit(f"skipped refs with untrustworthy paths: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
