vulnerabilities:
  - id: CVE-2024-47554
    statement: Ignore commons-io somewhere in the maven dependency tree
    expired_at: 2026-05-01
  - id: CVE-2025-67721
    statement: Ignore aircompressor until updated
    expired_at: 2026-05-01
  - id: CVE-2026-0861
    statement: Wait for upstream fix in debian
    expired_at: 2026-05-01
  - id: CVE-2023-45853
    statement: Wait for upstream fix in debian
    expired_at: 2026-05-01
  - id: CVE-2026-22695
    statement: Wait for upstream fix in debian
    expired_at: 2026-05-01
  - id: CVE-2026-22801
    statement: Wait for upstream fix in debian
    expired_at: 2026-05-01
